language: java

script: mvn verify

jdk:
 - openjdk8

cache:
  directories:
  - $HOME/.m2

notifications:
  email:
    recipients:
     - eg.oss@e-gineering.com

after_success:
  - mvn jacoco:report coveralls:report
